### ISSUE TITLE
taro2项目引入报错

### ISSUE THREAD

**Issue by lexmin0412** [CANntyield/taro-plugin-compiler-optimization#1]
taro2项目引入后开始编译即会失败。

![image](https://user-images.githubusercontent.com/24385370/138324857-fb66aea9-9b23-45d6-a62c-e217a984b26e.png)

**Comment by HyperLife1119** [comment]
好像还不支持taro3 vue3

**Comment by bluekurk** [comment]
研究半天发现Taro2没用 babel-loader(babel 6.x 还不支持 tsx), 貌似用的babylon+plugin, 看作者有没有时间支持下老版本了

**Comment by ct-0902** [comment]
这个报错是不支持ts编译，作者啥时候能处理兼容下ts

**Comment by CANntyield** [comment]
该插件支持taro3 react，小程序端。暂未考虑其他场景
