### ISSUE TITLE
使用这个插件后px不被转换为rpx

### ISSUE THREAD

**Issue by ShawnZeng** [CANntyield/taro-plugin-compiler-optimization#10]
![image](https://user-images.githubusercontent.com/29124100/175975057-8b016d29-f230-437b-b378-8547511270c6.png)
如图，pxtransform里面有个blacklist  'at'，会禁止把带at字样的class转换px到rpx。
我有一个class叫 navig**at**e-box ，里面带at，没有被转换。但是，当我去掉:	selectorBlackList: ['at']后，重新编译，依然好像在使用blacklist 'at'。百思不得其解。直到我把plugins: ['taro-plugin-compiler-optimization'],去掉后，问题解决。
所以，估计['taro-plugin-compiler-optimization']没有更新我的配置，仍然使用旧的selectorBlackList，导致问题发生。是不是有类似缓存的东西导致这个问题。请检查一下。谢谢。

**Comment by CANntyield** [comment]
该插件使用了cache-loader缓存了scss，所以会有这个问题，我晚点更新一版本将scss缓存策略默认关闭吧

**Comment by CANntyield** [comment]
更新一下npm包，改下配置
`plugins: [
    ['taro-plugin-compiler-optimization', {
      closeScssCache: true, // 关闭cache-loader缓存scss策略
    }]
  ]
`
