### ISSUE TITLE
Taro v3.3.10 出错

### ISSUE THREAD

**Issue by hdbaiyu** [CANntyield/taro-plugin-compiler-optimization#2]
🙅   Failed to compile.

./src/app.config.ts
Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 4)
pages.get is not a function
    at Array.map (<anonymous>)

**Comment by cong1223** [comment]
我也遇到了，跟你一样，H5端。

**Comment by cong1223** [comment]
> 🙅 Failed to compile.
> 
> ./src/app.config.ts Module build failed (from ./node_modules/thread-loader/dist/cjs.js): Thread Loader (Worker 4) pages.get is not a function at Array.map ()

请问你解决了吗？我的问题跟你一致

**Comment by vibin-lin** [comment]
一样的问题, 3.3.12版本的

**Comment by cong1223** [comment]
我想知道你们less版本下是怎么做css缓存的，我觉得作者这个插件多多少少有点草率了

**Comment by LiCeline** [comment]
version: 3.4.0
Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 9)
nodeTransforms[i] is not a function
估计都是Thread Loader css问题了

**Comment by hdbaiyu** [comment]
我放弃了~

**Comment by cong1223** [comment]
> 我放弃了~

我解决了，这两天正在整理相关文章

**Comment by bluescurry** [comment]
> > 我放弃了~
> 
> 我解决了，这两天正在整理相关文章

能简单说下咋解决的吗，现在Taro最新版本这个插件根本没法用
