### ISSUE TITLE
hi，非常感谢你们

### ISSUE THREAD

**Issue by lifegit** [CANntyield/taro-plugin-compiler-optimization#3]
[编写插件，将 Taro 编译打包耗时缩短至三分之一 @智行小程序团队](https://mp.weixin.qq.com/s/Z79QhAlP8tBQn3mXQ11byQ)，

1.文章写的非常棒！我觉得你们可以直接在taro提pr帮助改进，这样大家开箱即可以享受到三分之一的耗时而不用特地配置。

2.虽然插件很棒，但是随着版本的迭代或者部分同学有同样的问题但没有看到你们的文章，这会导致他们很痛苦。

**Comment by lifegit** [comment]
再次感谢为开源而战！

**Comment by CANntyield** [comment]
可以的呢，后续将尝试直接配置在taro中
