### ISSUE TITLE
试了还是没差别

### ISSUE THREAD

**Issue by wen-dong** [CANntyield/taro-plugin-compiler-optimization#4]
用了还是没差别 babel-loader took 3 mins

**Comment by CANntyield** [comment]
请问用的是react吗，css用的sass还是less

**Comment by wen-dong** [comment]
> 请问用的是react吗，css用的sass还是less

是react, less跟sass好像都有

**Comment by CANntyield** [comment]
这个对于大项目可能会有较好的效果，因为thread-loader会有启动耗时
