### ISSUE TITLE
taro2 报错

### ISSUE THREAD

**Issue by wanghaomayu** [CANntyield/taro-plugin-compiler-optimization#5]
Taro v2.0.2

/Users/.../node_modules/@tarojs/cli/dist/build.js:31
                plugin.apply(this);
                       ^

TypeError: plugin.apply is not a function
    at /.../node_modules/@tarojs/cli/dist/build.js:31:24

使用：
config/index.js文件中
![image](https://user-images.githubusercontent.com/24777637/147344675-1090853f-2565-4876-9938-fdfebb23ebff.png)

**Comment by CANntyield** [comment]
插件针对taro3写的，不支持taro2
