### ISSUE TITLE
H5端打包报错

### ISSUE THREAD

**Issue by cong1223** [CANntyield/taro-plugin-compiler-optimization#6]
![image](https://user-images.githubusercontent.com/37927942/148522669-8c47582d-f084-419c-82e6-1a61333302df.png)

**Comment by CANntyield** [comment]
这个是因为thread-loader固有限制，无法解决哦

**Comment by anryzhang** [comment]
taro3 也遇到 了这个问题

**Comment by CANntyield** [comment]
> taro3 也遇到 了这个问题

该插件不支持h5端
